In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import os
import torch.nn as nn
import torch.nn.functional as F

In [2]:
# test autograd.grad
t = torch.Tensor([[2,4]])
t.requires_grad_(True)
x = t - 1
y = torch.sum(x**2,dim = 1)
dy_dx, = torch.autograd.grad(y ,x, y.new(y.shape).fill_(1),create_graph = True)

print(t)
print(x)
print(y)
print(dy_dx)
dy_dx.backward(torch.tensor((), dtype=torch.float32).new_ones(x.shape))
print(t.grad)

tensor([[2., 4.]], requires_grad=True)
tensor([[1., 3.]], grad_fn=<SubBackward0>)
tensor([10.], grad_fn=<SumBackward2>)
tensor([[2., 6.]], grad_fn=<MulBackward0>)
tensor([[2., 2.]])
